artefacts:
  - name: none
    path: ''
  - name: base
    path: '{root}'
  - name: j_file
    path: '{root}/$Extend/$UsnJrnl:$J'
    legacy: '{root}/$Extend/$UsnJrnl$J'
  - name: mft
    path: '{root}/$MFT'
  - name: recycle_bin
    path: '{root}/$Recycle.Bin'
    legacy: '{root}/RECYCLER'
  - name: pagefile
    path: '{root}/pagefile.sys'
  - name: user_dir
    path: '{root}/Users'
    legacy: "'{root}/Documents and Settings'"
  - name: consolehost_history
    path: '{root}/Users/*/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadline/ConsoleHost_history.txt'
  - name: amcache
    path: '{root}/Windows/AppCompat/Programs/Amcache.hve'
    legacy: '{root}/Windows/appcompat/Programs/Amcache.hve'
  - name: recentFileCache
    path: '{root}/Windows/AppCompat/Programs/RecentFileCache.bcf'
  - name: prefetch
    path: '{root}/Windows/Prefetch'
  - name: system32
    path: '{root}/Windows/System32'
  - name: system
    path: '{root}/Windows/System32/config/SYSTEM'
  - name: system_config
    path: '{root}/Windows/System32/config'
  - name: sum
    path: '{root}/Windows/System32/LogFiles/Sum'
  - name: objects
    path: '{root}/Windows/System32/wbem/Repository/OBJECTS.DATA'
  - name: winevt
    path: '{root}/Windows/System32/winevt/Logs'
    legacy: '{root}/Windows/System32/config'
  - name: temp
    path: '{root}/Windows/Temp'
  - name: chrome
    path: '{root}/Users'
    legacy: '{root}/Documents and Settings'
  - name: actCache
    path: '{root}/Users/*/AppData/Local/ConnectedDevicesPlatform/*/ActivitiesCache.db'
