artefacts:
  - name: winevt
    path: ?:\Windows\System32\winevt\Logs
    path_type: folder 

wiskers:
  - name: evtx_dump
    binary: fd
    args:  . -e evtx -p {input} -x .\tools\evtx_dump-v0.8.1.exe -o json -f {outfolder}{outfile}
    outfolder: FileExecution
    outfile: evtx_dump.json
    input: ?:\Windows\System32\winevt\Logs
    choco:
    github: https://github.com/omerbenamram/evtx.git
    deps_choco: fd
    deps_github:
  - name: rust_registry
    binary: reg_dump 
    args: --recover --recurse -t jsonl --input {input} --output {outfolder}{outfile}
    outfolder: Registry
    outfile: 
    github: https://github.com/strozfriedberg/notatin