artefacts:
  - name: winevt
    path: '{root}/Windows/System32/winevt/Logs'
    path_type: folder
  - name: base
    path: '{root}'
    path_type: folder
  - name: j_file
    path: '{root}/$Extend/$UsnJrnl:$J'
    path_type: file
  - name: mft
    path: '{root}/$MFT'
    path_type: file
  - name: recycle_bin
    path: '{root}/$Recycle.Bin'
    path_type: folder
  - name: pagefile
    path: '{root}/pagefile.sys'
    path_type: file
  - name: user_dir
    path: '{root}/Users'
    path_type: folder
  - name: consolehost_history
    path: '{root}/Users/*/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt'
    path_type: file
  - name: amcache
    path: '{root}/Windows/AppCompat/Programs/Amcache.hve'
    path_type: file
  - name: recentFileCache
    path: '{root}/Windows/AppCompat/Programs/RecentFileCache.bcf'
    path_type: file
  - name: prefetch
    path: '{root}/Windows/Prefetch'
    path_type: folder
  - name: system32
    path: '{root}/Windows/System32'
    path_type: folder
  - name: system
    path: '{root}/Windows/System32/config/SYSTEM'
    path_type: file
  - name: sum
    path: '{root}/Windows/System32/LogFiles/Sum'
    path_type: folder
  - name: objects
    path: '{root}/Windows/System32/wbem/Repository/OBJECTS.DATA'
    path_type: file
  - name: winevt
    path: '{root}/Windows/System32/winevt/Logs'
    path_type: folder
  - name: chrome
    path: '{root}/Users/*/AppData/Local/Google/Chrome/User Data/Default'
    path_type: folder
  - name: temp
    path: '{root}/Windows/Temp'
    path_type: folder
  - name: polars_test
    path: C:\Users\Gavin\code\win7-c-drive.E01
    path_type: folder
  - name: evtx_dump
    path: C:\Users\Gavin\code\win7-c-drive.E01\Artefacts\d\Windows\System32\winevt\Logs\Microsoft-Windows-TaskScheduler%4Operational.evtx
    path_type: file
    
wiskers:
  - name: evtx_dump
    binary: '{tool_path}\evtx_dump-v0.8.1.exe'
    args: -f {outfolder}/{outfile} -o jsonl --no-confirm-overwrite {input}
    outfolder: EventLogs
    outfile: evtx_dump.json
    input: evtx_dump
    github: https://github.com/omerbenamram/evtx.git
  - name: EvtxECmd
    binary: 'C:\Users\Gavin\code\wiskess\Get-ZimmermanTools\EvtxECmd\EvtxECmd.exe'
    args: '-d {input} --csv {outfolder} --csvf {outfile}'
    outfolder: EventLogs
    outfile: EvtxECmd-All.csv
    input: winevt
    github: https://github.com/EricZimmerman/evtx.git
  - name: MFTECmd
    binary: C:\Users\Gavin\code\wiskess\Get-ZimmermanTools\MFTECmd.exe
    args: '-f {input} --csv {outfolder} --csvf {outfile} --vss --dedupe'
    outfolder: FileSystem
    outfile: MFTECmd.csv
    input: mft
    github: https://github.com/EricZimmerman/MFTECmd.git
  - name: mft
    binary: '{tool_path}\mft-v0.8.1.exe'
    args: '-o csv -f {outfolder}/{outfile}'
    outfolder: FileSystem
    outfile: mft.csv
    input: mft
    github: https://github.com/omerbenamram/mft
  - name: polars timeline
    binary: py
    args: C:/Users/Gavin/Documents/GitHub/wiskess_srm/tools/polars_tln.py {input} {start_date} {end_date}
    outfolder: Timeline
    input: polars_test