artefacts:
  - name: winevt
    path: ?:\Windows\System32\winevt\Logs
    path_type: folder 
    
wiskers:
  - name: test
    binary: ls
    args:  -lah
    outfolder: TestBinary
  - name: test
    binary: echo
    args:  hello yes, got it working
    outfolder: TestBinary